version: '2.1'
services:
#  node_1:
#    cap_add:
#    - NET_ADMIN
#    network_mode: host
#    volumes:
#    - ./image/dts_shared_config:/dts/raw-transformation-service/config
#    image: seko/demo_node_1
#    ports:
#    - 3901:8080
  node_2:
    cap_add:
    - NET_ADMIN
    network_mode: host
    volumes:
    - ./image/dts_shared_config:/dts/raw-transformation-service/config
    image: seko/demo_node_2
    ports:
    - 3901:8080